name: Build Checklists

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Compile checklists
        uses: alexnj/aviation-checklist-compiler-action@main
        with:
          pdf_output_group_heading: false
          pdf_max_indented_text_height: 1000
